site_name: shopipy_utils
site_url: https://RichardOberdieck.github.io/shopipy_utils/
repo_url: https://github.com/RichardOberdieck/shopipy_utils
repo_name: shopipy_utils

theme:
  name: "material"
  features:
    - content.code.copy
  palette: 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode


plugins:
  - search
  - mkdocstrings
