name: Update Ratings
on: 
    schedule:
      - cron: "30 * * * *"
  
env:
  SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

jobs:
  execute:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install hatch
        run: pip install hatch
      - name: Run script
        run: hatch run update_ratings
        shell: sh
